### PR TITLE
api funcs split out of makehandler

### PR DESCRIPTION
**Pull request by ds0nt**

### CODE REVIEW

**Comment by ds0nt** [comment]
So I've added some unit tests. They are useful for testing out the api as you write it. It's a lot faster than fiddling with postman and curl. And is good practice!

https://onsi.github.io/ginkgo/

```
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

ginkgo
```

Also I have changed the root package to be called `convolvr` instead of `main`

It is wrapped in the `cmd/main.go`

so to build it you should do this:

```
cd cmd
go build
```

**Comment by ds0nt** [comment]
Normally what I would do is create the endpoint. Once I think it might work, then I write the unit tests and prove that it works.

Then you can just plug it into your JS and know things are working on the go side of things. It's also useful for teams of people, as I don't necessarily want to touch the javascript code but do want to make sure my endpoint is working. Keepin' it locked down. It's also handy for testing it in a variety of ways, as opposed to just the success case that is first added into the client. :)

Anyways. merge me!

**Comment by ds0nt** [comment]
It might take a bit of cleanup too :p

**Comment by ds0nt** [comment]
Might need a git ignore for the binary .  And maybe a makefile or build.sh
and a .bin folder.

**Comment by SpaceHexagon** [comment]
screenshot_485
...possibly

**Comment by ds0nt** [comment]
oh yo, you need to make a gopath properly

https://golang.org/doc/code.html#GOPATH

you'll need a path like: some_place/go/src/github.com/SpaceHexagon/convolvr

**Pull request merged**
